### ISSUE TITLE
managed_components\joltwallet__littlefs\mklittlefs && make dist error

### ISSUE THREAD

**Issue by staunchheart** [joltwallet/esp_littlefs#103] opened 2022-10-21 12:44 UTC
windows 10 
mingw gcc 8.10

MAKE Version 5.2  Copyright (c) 1987, 1998 Inprise Corp.
Error makefile 3: Command syntax error
Error makefile 4: Command syntax error
Error makefile 6: Command syntax error
Error makefile 8: Command syntax error
......

**Comment by BrianPugh** [comment] 2022-10-21 14:42
Duplicate of #102

**Closed by BrianPugh** 2022-10-21 14:42 UTC
